#! /bin/sh
rm -f fabrique.zip 
rm -f fabrique.tgz
rm -f *~
rm -f */*~
rm -f */*/*~
rm tmp/*
cd ..
zip -r fabrique.zip fabrique/*
tar czfh fabrique/fabrique.tgz  fabrique/*
mv fabrique.zip fabrique/
cd fabrique